sudo: false

language: 
  - java

jdk: 
  - oraclejdk9

services:
  - docker
  - postgresql

addons:
  postgresql: "9.6"
  sonarcloud:
    organization: "ressec-github"
    projectKey: "ressec_hemajoo-gaming"
    token:
      secure: "${SONAR_TOKEN}"

cache:
  - $HOME/.m2
  #- target/

before_script:

script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -f hemajoo-gaming-atlas-parent/pom.xml

deploy:
  provider: script
  script: "cp hemajoo-gaming-atlas-parent/etc/deploy-settings.xml $HOME/.m2/settings.xml && mvn deploy -f hemajoo-gaming-atlas-parent/pom.xml"
  skip_cleanup: false
  on:
    # Set 'tags' to:
    # . 'true'  which will force the deployment of the artifact after a successful build only when the commit is tagged. So even if a merge request to 'master' is
    #           successful, the built artifact will not be deployed to the repository.
    # . 'false' which will force the deployment of the artifact after a successful build only when merged on the 'master' branch.
    tags: false

notifications:
  email:
    recipients:
    - christophe.resse@gmail.com
    on_success: change
    on_failure: always
  slack:
    rooms:
      # hemajoo is the Slack workplace
      # travis-gaming is the channel
      - hemajoo:lOkFRXlNg0sP7EhvnGUq3gZJ#travis-gaming